// lib/initialData.ts
import { Template, Agent, User } from '../types';

export const INITIAL_TEMPLATES: Record<string, Template> = {
  sales_pitch: { name: "Sales Pitch", description: "Persuasive storytelling with proof and next steps.", blueprint: [ { template: "title", title: "{topic} delivers measurable value", bullets: ["{tagline}"] }, { template: "executive_summary", title: "Lead with impact, evidence and a clear ask", bullets: ["Client problem & promised benefit", "Differentiators proving credibility", "Decision needed from stakeholders"] }, { template: "agenda", title: "This conversation guides you from context to commitment", bullets: ["Context: why change is required", "Solution: how our offer solves the problem", "Evidence: proof-points and data", "Next steps: clear actions"] }, { template: "content_visual", title: "Our solution addresses the client's urgent challenge", bullets: ["Describe client's current pain", "Explain the proposed capability", "Quantify the impact"] }, { template: "content_visual", title: "Evidence demonstrates we can deliver reliably", bullets: ["Share relevant case study results", "Outline the delivery approach", "Detail risk mitigation"] }, { template: "conclusion", title: "We close with agreed actions and a momentum-building ask", bullets: ["Reinforce the value proposition", "State the specific decision/next step", "List owners and timelines"] }, ] },
  strategy_update: { name: "Strategy Update", description: "Structured progress update for leadership routines.", blueprint: [ { template: "title", title: "Our strategy execution keeps us ahead", bullets: ["{tagline}"] }, { template: "executive_summary", title: "Achievements, challenges and required support", bullets: ["Key wins since last update", "Obstacles and root causes", "Decisions or resources needed"] }, { template: "agenda", title: "Progress, learnings and forward priorities", bullets: ["Impact delivered", "Lessons learned", "Priorities for next quarter"] }, { template: "content_visual", title: "Our KPIs signal momentum", bullets: ["Show metrics vs. targets", "Explain performance drivers", "Highlight customer feedback"] }, { template: "content_visual", title: "Key initiatives keep us on track", bullets: ["Outline flagship initiatives", "Share milestones", "Flag dependencies"] }, { template: "conclusion", title: "Leadership alignment unlocks the next wave of results", bullets: ["Summarise strategic implications", "Confirm commitments", "Define checkpoints"] }, ] },
};

export const INITIAL_AGENTS: Record<string, Agent> = {
    strategist: { id: 'strategist', name: 'Deck Strategist', systemPrompt: `You are an expert presentation writer and business strategist. Your task is to generate compelling content for a PowerPoint presentation based on a user's prompt and a predefined slide structure.` },
    creative_storyteller: { id: 'creative_storyteller', name: 'Creative Storyteller', systemPrompt: `You are a masterful storyteller. Your task is to generate presentation content that is engaging, narrative-driven, and uses evocative language. You focus on building a compelling story arc throughout the deck.`},
    copy_editor: { id: 'copy_editor', name: 'Copy Editor', systemPrompt: `You are a world-class copy editor. You tighten language, improve clarity, and ensure a professional and impactful tone.` },
    visual_designer: { id: 'visual_designer', name: 'Visual Designer', systemPrompt: `You are a visual designer AI. You suggest imagery, chart types, and layout improvements to make slides more visually engaging.` },
    summarizer: { id: 'summarizer', name: 'Summarizer Agent', systemPrompt: `You are an AI assistant that analyzes presentation content. Given the text from all slides in a deck, your job is to generate a concise, high-level executive summary (2-3 sentences) and extract the top 3-5 most important "Key Insights" as a bulleted list. The output must be a valid JSON object with two keys: "summary" and "keyInsights".` },
    speaker_notes_genius: { id: 'speaker_notes_genius', name: 'Speaker Notes Genius', systemPrompt: `You are a world-class public speaking coach. Your task is to generate concise yet powerful speaker notes for a presentation slide. For each slide, you will be given the title and a list of bullet points. Your notes should not just repeat the text on the slide, but add value by providing: 1. A compelling opening hook. 2. Deeper explanations or examples for each bullet point. 3. Cues for delivery (e.g., 'Pause for emphasis here', 'Make eye contact'). 4. A transition sentence to the next slide. Keep the notes for each slide to a reasonable length and format them as a single paragraph.` }
};

export const INITIAL_USERS: User[] = [
    { id: 'user1', name: 'Claus Jensen', role: 'Team Member', points: 1250 },
    { id: 'user2', name: 'Anna Schmidt', role: 'Administrator', points: 2800 },
    { id: 'user3', name: 'Peter Hansen', role: 'Read Only', points: 950 },
    { id: 'user4', name: 'Maria Garcia', role: 'Content Manager', points: 1800 },
];